version: '3.3'

#How to run
#docker-compose up --build -d
#docker-compose up -d
#docker-compose down
#docker-compose exec web sh

networks:
  default:
    driver: bridge

services:
  
  mariadb:
    image: mariadb:latest
    #restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_USER: uTestYii
      MYSQL_PASSWORD: kj7hghkl98GF
      MYSQL_DATABASE: testYii
    ports:
    - "8889:3306"
      
  web:
    image: yiisoftware/yii2-php:7.4-apache
    ports:
      - 808:80
    volumes:
      - ./src/basic:/app
      #- ./src/basic/web:/app/web
    links: 
      - mariadb:db
    depends_on:
      - mariadb
    build:
      context: ./web
      dockerfile: Dockerfile
      
  browser:
    image: selenium/standalone-chrome-debug:3.141.59    
    ports:
      - 4444:4444
